openapi: 3.0.3

#https://editor.swagger.io/

info:
  title: Laravel Xcode Project
  version: 1.0.0

servers:
  - url: http://localhost/api

paths:
  '/user-group':
    get:
      summary: list all user group
      tags:
        - "User Group"
      responses:
        '200':
          description: return objects from user_groups
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    example: [{ id: 1, name: "Root" },{ id: 2, name: "User" }]
    post:
      summary: create a new user group
      tags:
        - "User Group"
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: return objects from user_groups
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  update:
                    type: string
                    format: date-time
                  deleted_at:
                    type: null

  '/user-group/{user_group}':
    get:
      summary: show details from user group
      tags:
        - "User Group"
      parameters:
        - name: "user_group"
          in: path
          description: "ID of user group to return"
          required: true
          format: int
      responses:
        '200':
          description: return objects from user_groups
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  update:
                    type: string
                    format: date-time
                  deleted_at:
                    type: null
    put:
      summary: update an user group
      tags:
        - "User Group"
      parameters:
        - name: "user_group"
          in: "path"
          description: "ID of user group to return"
          required: true
          format: int
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: return boolean succes
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean

    delete:
      summary: delete an user group
      tags:
        - "User Group"
      parameters:
        - name: "user_group"
          in: path
          description: "ID of user group to delete"
          required: true
          format: int
      responses:
        '200':
          description: return boolean succes
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean


